// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NomisDbCaseStudy.Data;

#nullable disable

namespace NomisDbCaseStudy.Migrations
{
    [DbContext(typeof(NomisDbContext))]
    partial class NomisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NomisDbCaseStudy.Models.Body", b =>
                {
                    b.Property<int>("IDBody")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBody"));

                    b.Property<Guid>("BodyGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IDBody");

                    b.ToTable("Body", (string)null);
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.BodyBodyTable", b =>
                {
                    b.Property<int>("IDBodyBodyTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBodyBodyTable"));

                    b.Property<Guid>("BodyGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TableGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IDBodyBodyTable");

                    b.HasIndex("BodyGUID");

                    b.HasIndex("TableGUID");

                    b.ToTable("BodyBodyTable", (string)null);
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.BodyTable", b =>
                {
                    b.Property<int>("IDBodyTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBodyTable"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TableGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IDBodyTable");

                    b.ToTable("BodyTable", (string)null);
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.Element", b =>
                {
                    b.Property<int>("IDElement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDElement"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TableGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IDElement");

                    b.HasIndex("TableGUID");

                    b.ToTable("Element", (string)null);
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.Person", b =>
                {
                    b.Property<int>("IDPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPerson"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PersonGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IDPerson");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.PersonBody", b =>
                {
                    b.Property<int>("IDPersonBody")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPersonBody"));

                    b.Property<Guid>("BodyGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IDPersonBody");

                    b.HasIndex("BodyGUID");

                    b.HasIndex("PersonGUID");

                    b.ToTable("PersonBody", (string)null);
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.PersonInformation_11111111111111111111111111111111", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BodyGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("PersonInformation_11111111111111111111111111111111");
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.BodyBodyTable", b =>
                {
                    b.HasOne("NomisDbCaseStudy.Models.Body", "Body")
                        .WithMany("BodyBodyTables")
                        .HasForeignKey("BodyGUID")
                        .HasPrincipalKey("BodyGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomisDbCaseStudy.Models.BodyTable", "BodyTable")
                        .WithMany()
                        .HasForeignKey("TableGUID")
                        .HasPrincipalKey("TableGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("BodyTable");
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.PersonBody", b =>
                {
                    b.HasOne("NomisDbCaseStudy.Models.Body", "Body")
                        .WithMany("PersonBodies")
                        .HasForeignKey("BodyGUID")
                        .HasPrincipalKey("BodyGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomisDbCaseStudy.Models.Person", "Person")
                        .WithMany("PersonBodies")
                        .HasForeignKey("PersonGUID")
                        .HasPrincipalKey("PersonGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Body");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.Body", b =>
                {
                    b.Navigation("BodyBodyTables");

                    b.Navigation("PersonBodies");
                });

            modelBuilder.Entity("NomisDbCaseStudy.Models.Person", b =>
                {
                    b.Navigation("PersonBodies");
                });
#pragma warning restore 612, 618
        }
    }
}
